version: 2
updates:
  # Enable version updates for Maven
  - package-ecosystem: "maven"
    directory: "/backend"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    reviewers:
      - "sarihammad"
    assignees:
      - "sarihammad"
    commit-message:
      prefix: "chore"
      include: "scope"

  # Enable version updates for npm
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    reviewers:
      - "sarihammad"
    assignees:
      - "sarihammad"
    commit-message:
      prefix: "chore"
      include: "scope"

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    reviewers:
      - "sarihammad"
    assignees:
      - "sarihammad"
    commit-message:
      prefix: "chore"
      include: "scope"
