services:
  postgres:
    image: postgres:15
    container_name: codeshare_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: codeshare
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    container_name: codeshare_redis
    ports:
      - "6379:6379"

  kafka:
    image: bitnami/kafka:3.6
    container_name: codeshare_kafka
    ports:
      - "9092:9092"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper

  zookeeper:
    image: bitnami/zookeeper:3.8
    container_name: codeshare_zookeeper
    ports:
      - "2181:2181"

  backend:
    build:
      context: ./backend
    container_name: codeshare_backend
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - redis
      - kafka
