# Local development profile - safe defaults without secrets
spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  data:
    redis:
      host: localhost
      port: 6379
  kafka:
    bootstrap-servers: localhost:9092

# Local development settings
jwt:
  secret: local-development-secret-key-not-for-production
  expiration: 86400000

s3:
  enabled: false

# Management endpoints for local development
management:
  endpoints:
    web:
      exposure:
        include: "*"

